stages:
  - build
  - deploy
variables:
  DOCKER_DRIVER: overlay2 
services:
  - docker:dind  
build:
  stage: build
  script: 
    - docker build -f Dockerfile . -t ozguro/bitcoin-app:latest 
    - docker push ozguro/bitcoin-app:latest 
deploy:
  stage: deploy
  script:
    - ssh -i /vagrant/.vagrant/machines/master/virtualbox/private_key vagrant@192.168.56.13 sudo kubectl apply -f /vagrant/deployment/deployment.yaml
  only:
    - merge_requests
    - main
  tags:
    - bitcoin-app

